name: CI
on:
  push:
    branches: [ development ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/xfhg/intercept:1.0.12-linux-amd64@sha256:58affc84e5f3709419505c9ae6bb803bf81662ffc439e5aa280eab43e8e89714
      env:
        test: development
      options: --cpus 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run intercept with mock policy
        run: |
          intercept audit --policy playground/policies/mock_github.yaml --target playground/targets/ -vvvv 