name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/xfhg/intercept:1.0.12-linux-amd64@sha256:81796fbf9eeebf096ba3d4bdf3b40a7ddd298f9a43650dc10f8a22fc5b92c479
      env:
        test: development
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)